version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/MakeNowJust/constraint
    steps:
      - checkout
      - run:
          name: Prepare
          command: |
            go get -v -t -d ./...
      - run:
          name: Run test
          command: |
            go test -v -cover -race -coverprofile=coverage.txt ./...
      - run:
          name: Send coverage
          command: |
            bash <(curl -s https://codecov.io/bash)
